### ISSUE TITLE
Provide js and html code listings for the Web Examples

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/NASAWorldWind.github.io#141]
The Web Examples would be much more useful if the html and JavaScript code accompanied the each example, thus allowing the viewer to easily copy/paste the relevant example code into their own projects.

Even better would be embedding be a live coding sandbox ala [JSBin](http://jsbin.com/help/how-can-i-embed-jsbin), thus allowing viewers to see and edit the code and realize the result of their changes immediately.

**Comment by emxsys** [comment]
JSBin on GitHub: https://github.com/jsbin/jsbin

**Comment by pdavidc** [comment]
@eirizarry just a heads up that @emxsys reminded me that we can host JSBin demos on the WorldWind domain, if we choose to so. Since JSBin is an open source project, access to the server side software is readily available.

The concepts that @emxsys outlines in pull request #142 is certainly the direction we want to go with WebWorldWind's demonstrations. There's no urgency to implementing these changes, but take a moment to review the concepts, and think about when might be a good time to incorporate this into the WebWorldWind project.
