### ISSUE TITLE
Alternative site generation options

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/NASAWorldWind.github.io#7]
What site generation options are available that can do the following:

1. Work within Travis-CI and on a local machine
2. Build static site and utilize Travis deploy functionality to GH Pages
3. Easy to use and pick up
4. Lots of formal and informal documentation/examples

Examples:
Jekyll, Hugo, Roots

**Comment by eirizarry** [comment]
If we want something that can be "new" whenever someone needs to change something, Hugo seems like a good fit. We can use Travis to deploy functionality, installation and usage are very simple, and there is quite a bit of documentation. Other generators like Jekyll, Middleman, and Nanoc are more complicated and use Ruby as a package manager. 

However, it's not clear to me how this will let us visualize World Wind examples on the web page.

**Comment by AkeluX** [comment]
First, a disclaimer. I use Jekyll and don't know Hugo and the others so well.

Personally, I don't find Jekyll complicated at all. There is some learning to do with all of them. You mention Ruby, but the same argument is true for Hugo that is built in Go. It's a matter of personal/team preferences I would say.

More importantly, GitHub Pages have native support for Jekyll and can thus generate your site without Travis-CI involved. This isn't without limitation because GitHub offers some Jekyll add-ons, but you can't add your own or custom ones. See https://help.github.com/articles/about-github-pages-and-jekyll/

Another big advantage is that with Jekyll, GitHub Pages provide you with some metadata about your repository and releases to put in your templates. See https://help.github.com/articles/repository-metadata-on-github-pages/

From my point of view, we need stronger arguments for not using what is natively supported and encouraged by GitHub for this particular case, e.g. something we couldn't do at all for example.

Some examples:
https://github.com/artsy/artsy.github.io
https://github.com/Shopify/shopify.github.com
https://github.com/guardian/guardian.github.com
https://github.com/cfpb/cfpb.github.io
https://github.com/square/square.github.io

**Comment by zglueck** [comment]
@AkeluX you raise some excellent points. As part of our website "build" process, we are intending to download zip files, unzip, and then post them as part of the website. Is this a task Jekyll can accomplish as part of its build process without using plugins?

We were imagining an npm script handling our dynamic content retrieval and generation (very similar to the current one) and then utilizing a static site generator to produce the final content. This would all occur in Travis with a Travis GitHub pages deployment publishing the content.

I was leaning toward Hugo because of the built-in toolset and portability. As you pointed out, Jekyll isn't terribly complicated to use or install, but compared to Hugo, the install process is far more involved if we want to work on something locally (especially for our Windows bretheren @emxsys ;)

From my research, Jekyll and Hugo seem very similar in terms of creating content, templating, and local toolset. I think they are set apart in the installation, and as you pointed out, GitHub integration. I'm not sure we can leverage the GitHub integration with some of the tasks we want to accomplish which makes the ease of Hugo install a bit more appealing.

What are your thoughts on Foundation vs Bootstrap? :)

**Comment by pdavidc** [comment]
@AkeluX and @zglueck, I had the same strong concern about using a 3rd party tool to build a GitHub pages site, especially when Jekyll is natively supported and encouraged.

Here's the key argument for why we're looking at 3rd party site generators: the desire to publish this site at our official domain. The HTTP server running this domain is a basic Apache server, which I'm very hesitant to modify, and it cannot redirect to the GitHub pages domain. These are beuracratic limitations, not technical ones. Given that, my conclusion has been that the content of the master branch must be a basic HTML+CSS+JS site we can deploy anywhere. I realize this is an unusual use case for GitHub pages.

That said, I'm new to this technology and may have overlooked something. Given this and @zglueck's comments, what are your thoughts?

**Comment by zglueck** [comment]
We mocked up example sites with the static site generators: Hugo, Jekyll, and Metalsmith. After evaluating each against our primary requirements of: substantial documentation, ease of use/install, embedding "dynamic" content in markdown, and the put it down and pick up six months later, we've identified Hugo as the best option.

Hugo's particular strengths included shortcodes, ease of install, documentation, and included tooling. Additionally, the initial mock-ups of Hugo's integration with Travis revealed a solution that wasn't overly complex. A full comparison of the different generators is available at: 

https://github.com/zglueck/site-compare/
